### PR TITLE
Manage Package Versions Centrally applyed and ABP 9.0.0 upgraded, packs version setting to 0.9.6

### PR DESCRIPTION
**Pull request by dolunay**

### CODE REVIEW

**Comment by realLiangshiwei** [comment]
Thanks @dolunay. 
Could you upgrade all packages to the latest version (ABP, Antdesign etc..)?
if you don't have time, I can do that.

**Comment by dolunay** [comment]
> Thanks @dolunay. Could you upgrade all packages to the latest version (ABP, Antdesign etc..)? if you don't have time, I can do that.

Working on ABP 9.0 and AntDesign 1.0.1 upgrade.

**Comment by dolunay** [comment]
> ABP 9.0 and AntDesign 1.0.1 upgrade

completed. .DbMigrator, .Blazor, .Blazor.Server and .HttpApi.Host tested and working.

**Comment by realLiangshiwei** [comment]
Thanks @dolunay

**Pull request merged**
